# Settings for the chart.

# nameOverride Replaces the release name of the chart in Chart.yaml file when
# this is used to construct Kubernetes object names
nameOverride: ""
# fullnameOverride completely replaces the generated release name
fullnameOverride: ""

builder:
  # Secrets to pull container images from private registries
  imagePullSecrets: []
  image:
    # osbuilder image to be used. Leave empty to use the default
    repository: ghcr.io/pluralsh/osbuilder
    # tag of the osbuilder image. Leave empty to use chart's AppVersion
    tag: ~

  replicas: 1

  # The PVC storage size for the build process
  pvcStorageSize: "30Gi"

  toolsImage:
    repository: "quay.io/kairos/auroraboot"
    tag: "latest"

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ## Resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    controller:
      limits:
        cpu: 500m
        memory: 50Mi
      requests:
        cpu: 250m
        memory: 50Mi

registry:
  enabled: false
  # Secrets to pull container images from private registries
  imagePullSecrets: []
  image:
    # docker container registry image to be used. Leave empty to use the default
    repository: registry
    # tag of the docker container registry image. Leave empty to use chart's AppVersion
    tag: 2

  # Number of replicas for the registry
  replicas: 1

  # Whether registry should be set to debug level and expose debug server on port 5001
  debug: false

  storage:
    # Currently only s3 is supported
    driver: s3
    s3:
      accessKey: ~
      secretKey: ~
      region: ~
      bucket: ~
      endpoint: ~

  auth:
    # Currently only 'basic-realm' with htpasswd file is supported. Use "~" to disable auth.
    realm: basic-realm
    htpasswd:
      # When existingSecret is provided it will ignore the rest of htpasswd configuration
      # and not generate the secret. It should provide a valid htpasswd file under the "htpasswd" secret key.
      existingSecret:
        name: ~
      # Default username embedded in autogenerated htpasswd secret.
      username: plural
      # Secret that stores a password that should be encrypted and stored in autogenerated htpasswd file.
      secret:
        name: ~
        key: password

  ingress:
    enabled: true
    ingressClass: nginx
    dns: ~

    tls:
      enabled: true

    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'

  # Defines extra env vars that should be passed to the registry containers.
  # Can be used to customize the configuration
  #
  # Example format (<ENV_VAR_NAME>: <ENV_VAR_VALUE>):
  #
  # extraEnvVars:
  #   REGISTRY_HTTP_ADDR: ':5000'
  #   REGISTRY_HTTP_DEBUG_ADDR: ':5000'
  #   WEIRD_TEXT_WITH_SPECIAL_CHARTS: '":-g*_Asd123gj$$"'
  extraEnvVars: {}

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# It is required to create certificates.
certManager:
  enabled: false