kind: Secret
apiVersion: v1
metadata:
  name: registry-config
  namespace: osbuilder
stringData:
  config.json: |
    {
    "auths": {
    "https://index.docker.io/v1/": {
      "auth": "CHANGE ME"
        }
      }
    }
---
kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: osbuilder
stringData:
  userdata: |
    #cloud-config
    hostname: plural-edge-{{ trunc 10 .MachineID }}
    
    users:
      - name: "test"
        passwd: test
        groups: [ "admin" ]
    
    write_files:
      - path: /etc/rancher/k3s/registries.yaml
        permissions: "0644"
        content: |
          mirrors:
            "*":  
    
    k3s:
      enabled: true
      replace_args: true
      args:
        - --node-name=kairos
        - --embedded-registry
        - --disable=traefik,servicelb
    
    bundles:
      - targets:
          - run:///plural-bundle.tar
        local_file: true
      - targets:
          - run:///plural-images-bundle.tar
        local_file: true
      - targets:
          - run:///plural-trust-manager-bundle.tar
        local_file: true    

    plural:
      token: CHANGE_ME
      url: https://console.plrl-dev-aws.onplural.sh
---
kind: OSArtifact
apiVersion: build.kairos.io/v1alpha2
metadata:
  name: kairos-plural
  namespace: osbuilder
spec:
  imageName: "quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1"
  iso: true
  model: rpi4
  fileBundles:
    plural-bundle: ghcr.io/pluralsh/kairos-plural-bundle:0.1.4
    plural-images-bundle: ghcr.io/pluralsh/kairos-plural-images-bundle:0.1.1
    plural-trust-manager-bundle: ghcr.io/pluralsh/kairos-plural-trust-manager-bundle:0.1.0
  cloudConfigRef:
    name: cloud-config
    key: userdata
  exporter:
    registry:
      name: index.docker.io
      image:
        repository: test/kairos
        tag: latest
      dockerConfigSecretKeyRef:
        name: registry-config
        key: config.json

