{{- if and (eq .Values.registry.auth.realm "basic-realm") (not .Values.registry.auth.htpasswd.existingSecret.name) (.Values.registry.enabled) }}

{{- if not .Values.registry.auth.htpasswd.secret.name }}
  {{- fail "A valid .Values.registry.auth.htpasswd.secret.name required when auth realm set to 'basic-realm'" }}
{{- end }}

{{ $passwordSecret := lookup "v1" "Secret" .Release.Namespace .Values.registry.auth.htpasswd.secret.name }}

{{- if not $passwordSecret.data }}
  {{- fail "Could not find secret provided via .Values.registry.auth.htpasswd.secret.name" }}
{{- end }}

{{ $password := index $passwordSecret.data .Values.registry.auth.htpasswd.secret.key | b64dec }}

{{- if not $password }}
  {{- fail "Could not find password key value in the provided secret" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: registry
    {{- include "helm-chart.labels" . | nindent 4 }}
stringData:
  htpasswd: {{ htpasswd .Values.registry.auth.htpasswd.username $password }}

{{- end }}