apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: osartifactbuilder-operator-leader-election-role
    namespace: '{{.Release.Namespace}}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: osartifactbuilder-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - build.kairos.io
    resources:
      - osartifacts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - build.kairos.io
    resources:
      - osartifacts/finalizers
    verbs:
      - update
  - apiGroups:
      - build.kairos.io
    resources:
      - osartifacts/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: osartifactbuilder-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: osartifactbuilder-operator-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: osartifactbuilder-operator-leader-election-rolebinding
    namespace: '{{.Release.Namespace}}'
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: osartifactbuilder-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: osartifactbuilder-operator-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: osartifactbuilder-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: osartifactbuilder-operator-proxy-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: osartifactbuilder-operator-proxy-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
