apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: {{ include "osartifact.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  imageName: {{ .Values.image }}
  iso: true
  {{- if .Values.device }}
  model: {{ .Values.device }}
  {{- end }}
  fileBundles:
    {{- range $key, $value := .Values.defaultBundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.bundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.extraBundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
  cloudConfigRef:
    name: {{ include "osartifact.fullname" . }}-config
    key: cloud-config.yaml
  exporter:
    serviceAccount: {{ include "osartifact.fullname" . }}
    {{- with .Values.exporter.extraEnvVars }}
    extraEnvVars: {{ . | toYaml | nindent 4 }}
    {{- end }}
    registry:
      name: {{ .Values.exporter.registry.name }}
      type: {{ .Values.exporter.registry.type }}
      image:
        repository: {{ .Values.exporter.registry.image.repository }}
        tag: {{ .Values.exporter.registry.image.tag }}
      {{- if (eq .Values.exporter.registry.type "other") }}
      passwordSecretKeyRef:
        name: {{ .Values.exporter.registry.configSecret.name | default (printf "%s-%s" (include "osartifact.fullname" .) "config") }}
        key: {{ .Values.exporter.registry.configSecret.key }}
      {{- end }}