apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: {{ include "osartifact.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  imageName: {{ .Values.image }}
  iso: true
  {{- if .Values.device }}
  model: {{ .Values.device }}
  {{- end }}
  fileBundles:
    {{- range $key, $value := .Values.defaultBundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.bundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.extraBundles }}
    {{ $key }}: {{ $value }}
    {{- end }}
  cloudConfigRef:
    name: {{ include "osartifact.fullname" . }}-config
    key: cloud-config.yaml
  outputImage:
    cloud: {{ .Values.exporter.cloud }}
    registry: {{ .Values.exporter.registry }}
    repository: {{ .Values.exporter.repository }}
    tag: {{ .Values.exporter.tag }}
    {{- if (eq .Values.exporter.cloud "other") }}
    passwordSecretKeyRef:
      name: {{ .Values.exporter.configSecret.name | default (printf "%s-%s" (include "osartifact.fullname" .) "config") }}
      key: {{ .Values.exporter.configSecret.key }}
    {{- end }}