{{ $secret := (lookup "v1" "Secret" .Release.Namespace .Values.tokenSecret.name) }}

kind: Secret
apiVersion: v1
metadata:
  name: '{{ include "osartifact.fullname" . }}-cloud-config'
stringData:
  cloud-config.yaml: |
    #cloud-config
    hostname: plural-edge-{{ `{{ trunc 10 .MachineID }}` }}

    users:
      - name: {{ .Values.username }}
        passwd: {{ .Values.password }}
        {{- with .Values.defaultUser }}
        groups: [
         {{- range .groups -}}
          {{- if eq . ($.Values.defaultUser.groups | last) -}}
          "{{ . }}"
          {{- else -}}
          "{{ . }}",
          {{- end -}}
         {{- end -}}
        ]
        {{- if .ssh_authorized_keys}}
        ssh_authorized_keys:
        {{- .ssh_authorized_keys | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- if .Values.extraUserCloudConfig }}
      {{- .Values.extraUserCloudConfig | toYaml | nindent 6 }}
      {{- end }}

    write_files:
      - path: /etc/rancher/k3s/registries.yaml
        permissions: "0644"
        content: |
          mirrors:
            "*":

    k3s:
      enabled: true
      replace_args: true
      args:
        - --node-name={{ .Values.nodeName }}
        - --embedded-registry
        - --disable=traefik,servicelb

    bundles:
      - targets:
          - run:///plural-bundle.tar
        local_file: true
      {{- range $key, $value := .Values.defaultBundles }}
      - targets:
          - run://{{ $key }}.tar
        local_file: true
      {{- end }}
      {{- range $key, $value := .Values.bundles }}
      - targets:
          - run://{{ $key }}.tar
        local_file: true
      {{- end }}
      {{- range $key, $value := .Values.extraBundles }}
      - targets:
          - run://{{ $key }}.tar
        local_file: true
      {{- end }}

    plural:
      token: {{ index $secret .Values.tokenSecret.key }}
      url: {{ .Values.url }}

    {{- if .Values.extraUserCloudConfig }}
    {{ .Values.extraCloudConfig | toYaml | nindent 4 }}
    {{- end }}

