apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osartifact.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.exporter.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}