name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**'

concurrency:
  group: lint-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
jobs:
  call-workflow:
    uses: kairos-io/linting-composite-action/.github/workflows/reusable-linting.yaml@v0.0.10
    with:
      yamldirs: ".github/workflows/ config/"
      is-go: true
