name: Publish OS Artifact Chart

on:
  workflow_dispatch:
  push:
    paths:
      - charts/osartifact/**
    branches:
      - master

jobs:
  publish:
    name: Publish Helm Chart
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        id: release
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: "./.github/configs/cr.yaml"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
